### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by Slattsveen** [nexx512/txppm#2]
Hi, and thanks for pushing support of this program!

However, I'm getting a bunch of compilation errors. The first one I think I have a possible solution to. 
"ISO C90 forbids mixed declarations and code", found a fix here: https://stackoverflow.com/questions/13291353/iso-c90-forbids-mixed-declarations-and-code-in-c
On my system at least the compiler was defaulting to some outdated standard (c89). 
BTW, I'm running Linux Mint 18.2 64bit on an Intel Core duo p9700.

I added the following to the Makefile, and the ISO C90 error disapeared:
CC = gcc
ccflags-y = -Wall -std=c99

After this I run into some issues with the included kernel.h, which is far beyond my scope of understanding :) Error output from trying to "make" in the /module folder is attached.
[kernel_make_results.txt](https://github.com/nexx512/txppm/files/1528190/kernel_make_results.txt)

**Comment by nexx512** [comment]
Switching to c99 would be a good Idea. I will have a look at this.
However when you switch to c99, you will have to prefix the `asm` with underscores and use `__asm` instead (see https://stackoverflow.com/questions/755457/asm-in-c-gives-an-error-with-std-c99)
